# Generated by Django 3.2.5 on 2021-07-23 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Meetup title')),
                ('slug', models.SlugField(unique=True, verbose_name='Meetup slug')),
                ('organizer_email', models.EmailField(max_length=254, verbose_name='Organizer field')),
                ('description', models.CharField(max_length=255, verbose_name='Meetup description')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
