# Generated by Django 3.2.5 on 2021-07-23 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetup',
            name='description',
            field=models.TextField(verbose_name='Meetup description'),
        ),
        migrations.AlterField(
            model_name='meetup',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
